### PR TITLE
removed token lines from config.js

### PR DESCRIPTION
**Pull request by Fierythunder**
**Please describe the changes this PR makes and why it should be merged, as well as any and all proof of successful tests:**
Token is now present in `.env` so there is no need of having these lines for token in config.js
```
  // Your Bot's Token. Available on https://discord.com/developers/applications/me
  "token": "Replace me",
```
So, no need of hiding config.js in git ignore

**Semantic versioning classification:**

- [x] This PR changes the framework's interface (methods or parameters added)
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to README, etc.

### CODE REVIEW

**Comment by YorkAARGH** [comment]
Oh, thanks, I didn't realise I forgot to remove that.

However, I wouldn't remove it from the .gitignore, as people will still *probably* use it for tokens, or other sensitive data regardless of the `.env` or not.

**Comment by Chicken** [comment]
Config is a personal thing specific to a deployment, not something that should be pushed to version control anyway.

**Comment by RealShadowNova** [comment]
Generally, you'd have an example file, like `config.example.js` and then you'd copy the file and rename it to `config.js`. This helps keep sensitive files out of git, but still keeps that structure.

**Comment by Fierythunder** [comment]
ok, I will add it back to the .gitignore

**Pull request merged**
