### PR TITLE
Update setup.js

### PR DESCRIPTION
**Pull request by matheustorsani**
little detail (I forgot to put the "in" without login, sorry.)
this executes the commands, without which it can cause a possible error.

### CODE REVIEW

**Comment by eslachance** [comment]
This doesn't seem to do anything. What is the point of it?

**Comment by eslachance** [comment]
Actually this would error out because `console.login` isn't a function so it's not only pointless, it breaks the setup. I'm really curious as to what you're trying to do here.

**Comment by matheustorsani** [comment]
Hello! sorry for the delay in responding, I did not expect to receive
responses by email ...

Basically, in discord, there is something called TOKEN, using the token,
you are able to sign in to someone's account, And for discord to understand
what you are trying to connect, the token is necessary, that's why we use
console.login (config.token)


Em sex, 24 de jul de 2020 20:24, Évelyne Lachance <notifications@github.com>
escreveu:

**Comment by eslachance** [comment]
I love the condescending tone of your reply, as if we weren't aware what a token was. We've been writing guides, boilerplates and frameworks for over 4 years, and helped tens of thousands of people to get started with bots in this time. We know what a token is, thank you very much. 

So let me clarify a few things: 

- The "console" isn't the discord.js client. Console is used for outputting to console, so "console.log" is a way to output text to the console, for debugging or logging. So... "console.login" isn't anything, it doesn't exist. 
- The setup.js is not the bot, it doesn't need to login because it's meant to only configure the bot's files. That's why there is no client, which explains why you probably got confused between the "client" and "console". 
- Even if this *was* the bot and we *did* have a client variable, your code, exactly `console.login('token')` (or even `client.login('token')` does nothing because you're not actually pulling from the config at all, you're just sending the string called `token`. 

Perhaps you confused the PR system for support and guidance to understand how this code works. If that's the case, please join our Discord server and we'll be able to assist you in using GuideBot: https://discord.gg/4NE4bk7

**Pull request closed without merging**
