### PR TITLE
minor improvements namely for the times when the help msg is too long

### PR DESCRIPTION
**Pull request by nathanielcwm**
i have also changed the specific help msg a slight bit reverse that if u don't like it

### CODE REVIEW

**Comment by YorkAARGH** [comment]
I thank you for bringing this to my attention, I implemented something like this in my bot repo, but I forgot to add it to the guidebot repos,

If you could update your PR by [adding a zero-width space in front of the category name](https://github.com/YorkAARGH/York-Dev/blob/master/commands/support/help.js#L29), which means [you can split by that and have a beautifully organised help menu](https://github.com/YorkAARGH/York-Dev/blob/master/commands/support/help.js#L34), I will happily accept your PR.

**Comment by nathanielcwm** [comment]
ok sure!

**Comment by nathanielcwm** [comment]
@YorkAARGH i think i have it in however it only splits it on the last cat that should be ok right?

**Comment by YorkAARGH** [comment]
Yeah, that's the expected result, if splits at the nearest zero width
space, so the last category before the length is to long would be the one
that splits

**Comment by YorkAARGH** [comment]
Any chance you can fix the mistakes? (You used single quotes instead of double)

**Comment by nathanielcwm** [comment]
ok no prob

**Comment by nathanielcwm** [comment]
@YorkAARGH

**Comment by nathanielcwm** [comment]
wait fixing the other problems

**Comment by YorkAARGH** [comment]
Okay, final 2 things, 1) Do you have a screenshot to show the 'aliases' stuff? and 2) you are aware that it's an array right?

**Comment by nathanielcwm** [comment]
wait 1 moment

**Comment by nathanielcwm** [comment]
image

**Comment by nathanielcwm** [comment]
yeah ik its an array wait would this be better:
aliases:: ${command.conf.aliases.toString()} @YorkAARGH

**Comment by YorkAARGH** [comment]
try `.join(", ")`ing the array

**Comment by nathanielcwm** [comment]
thanks makes it look much nicer @YorkAARGH

**Pull request merged**
